language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t gentlemj/movie-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gentlemj/movie-app npm run test

after_success:
  - docker build -t gentlemj/movie-app-client ./client
  - docker build -t gentlemj/movie-app-server ./server
  - docker build -t gentlemj/movie-app-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push gentlemj/movie-app-client
  - docker push gentlemj/movie-app-server
  - docker push gentlemj/movie-app-nginx

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "ap-northeast-2"
  app: "movie-app"
  env: "MovieApp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-297348835951
  bucket_path: "movie-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
